###################################################################################
#
# https://docs.docker.com/compose/environment-variables/
#
###################################################################################

version: '3'
services:

  catmedb:
    image: mysql:8.0.30
    ports:
     - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPassword}"
      MYSQL_DATABASE: "${dbName}"
      MYSQL_USER: "${dbUsername}"
      MYSQL_PASSWORD: "${dbPassword}"
    volumes:
      - ./kdb:/var/lib/mysql
    user: ${MYSQL_UID}
